### PR TITLE
[fix] Fixed StorageCore throwing on playback while scan is still in-progress

### LINKED ISSUE #301: Crash if multiple playback during storage scan
### Describe the bug

App can be easily crashed by trying to play items while a file scan is active.

### Affected area

- [ ] Strix Music SDK
- [x] Strix Music App

### Regression

_No response_

### Steps to reproduce

```text
1. Set up a storage core (local files, onedrive, ipfs, doesn't matter)
2. Playback as soon as items appear
3. Try to change the item playing and observe the crash
```

### Visual repro steps

_No response_

### Expected behavior

No crash

### Additional context

Image

### Help us help you

Yes, I'd like to be assigned to work on this item.

### PR DESCRIPTION
**Pull request by Arlodotexe**
## Overview

Closes #301

## Checklist

This PR meets the following requirements:
- [x] Tested and contains **NO** breaking changes or known regressions.
- [x] Tested with the upstream branch merged in.
- [x] Tests have been added for bug fixes / features (or this option is not applicable)
- [x] All new code has been documented (or this option is not applicable)
- [x] Headers have been added to all new source files (or this option is not applicable)

## Additional info

`IFolderScanner` has a questionable API.
It should really implement IFolder instead of doing this all from scratch.
I'll just patch this and fix that later

### CODE REVIEW

File: src/Cores/Storage/src/StorageCore.cs [hunk 1]
```diff
@@ -215,9 +215,15 @@ public ValueTask DisposeAsync()
...
-        var file = FolderScanner.KnownFiles.ToArray().FirstOrDefault(x => x.Id == track.Id);
-        if (file is null)
+        IFile? file;
+        try
+        {
+            file = await FolderScanner.GetKnownFileByIdAsync(track.Id, cancellationToken);
+        }
+        catch (FileNotFoundException)
+        {
             return null;
```
Comment (amaid) [inline src/Cores/Storage/src/StorageCore.cs:225]: Should we log exceptions here?

File: src/Cores/Storage/src/FileMetadata/Scanners/DepthFirstFolderScanner.cs [hunk 2]
```diff
@@ -79,16 +88,25 @@ private async IAsyncEnumerable<IChildFile> RecursiveScanForFilesAsync(IFolder fo
     /// <inheritdoc/>
     public ObservableCollection<IChildFile> KnownFiles { get; } = new();
 
+    /// <inheritdoc/>
+    public async Task<IChildFile> GetKnownFileByIdAsync(string fileId, CancellationToken cancellationToken = default)
+    {
+        using (await _updateMutex.DisposableWaitAsync())
+        {
+            return KnownFiles.FirstOrDefault(x => x.Id == fileId)
```
Comment (amaid) [inline src/Cores/Storage/src/FileMetadata/Scanners/DepthFirstFolderScanner.cs:96]: KnownFiles is a dictionary, instead of Linq should we use TryGetValue?

**Review by amaid — CHANGES_REQUESTED** [review]
Functionality looks good just one question added as a comment that requires a response

File: src/Cores/Storage/src/FileMetadata/Scanners/DepthFirstFolderScanner.cs (hunk 2 above)
Comment (Arlodotexe) [reply src/Cores/Storage/src/FileMetadata/Scanners/DepthFirstFolderScanner.cs]: @copilot Please make this change, instead of Linq let's use TryGetValue
